PREFIX=•
AUTO_READ_STATUS=yes
AUTO_DOWNLOAD_STATUS=yes
PM_PERMIT=no
BOT_NAME=Zokou-Md
BOT_MENU_LINKS=https://files.catbox.moe/ak9lza.jpg
PUBLIC_MODE=no
HEROKU=no
Database_URL=postgresql://dyby_tech_4qfz_user:9DsAduUIO7ptua07mMhr31TIOSf39msH@dpg-csses9a3esus739m1aj0-a.oregon-postgres.render.com/dyby_tech_4qfz
NOM_OWNER=Lady
NUMERO_OWNER=+50943636193
WARN_COUNT=3
STARTING_BOT_MESSAGE=yes
Presence=3
PM_CHATBOT=no
SESSION_ID=2@WAbZzHnLbQ+rOqpWCgzeLcYuRFQ3uTzAGPTirbLtH59l3dsAHg6jD/kM+9nsdnTDEZNi4UdV3mgRaElUSRzaKq2iuHBCojmcOHc=,tqX8+aLItZHTUlP9NhiPlWRAVEcJ1CzUOjGhUiBZaGc=,dOFe7RpPdtsc6zhqKRYFFXWmc5Ok7eaSe9nTuY1mezc=,VdVJ1n25rgECoWjFjxReS5oMvYO3VG5HvB7AWUFRwDY=
ANTI_VIEW_ONCE=no
ANTI_COMMAND_SPAM=no
